

name: task1

on:
  push:
    branches:
      - master

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x task1.sh

      - name: Run task1.sh
        run: ./task1.sh

